# Generated by Django 5.1 on 2024-11-17 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0030_goodscomposition_name_type_of_goods_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Birtrix_Goods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bitrix_goods_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование товара для Битрикс')),
                ('price_material', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Цена за материал')),
                ('price_add_material', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Цена за добавочный материал')),
                ('price_salary', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Заработная плата')),
                ('price_payroll', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Отчисления на заработную плату')),
                ('price_overheads', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Накладные расходы')),
                ('price_cost', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Себестоимость')),
                ('price_profit', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Прибыль')),
                ('price_salary_fund', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Фонд заработной платы')),
                ('price_final_price', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Общая цена')),
                ('goods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.goods', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар для Битрикс',
                'verbose_name_plural': 'Товар для Битрикс',
            },
        ),
        migrations.CreateModel(
            name='Birtrix_Price_GoodsComposition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bitrix_goods_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование товара для Битрикс')),
                ('price_material', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Цена за материал')),
                ('price_add_material', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Цена за добавочный материал')),
                ('price_salary', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Заработная плата')),
                ('price_payroll', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Отчисления на заработную плату')),
                ('price_overheads', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Накладные расходы')),
                ('price_cost', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Себестоимость')),
                ('price_profit', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Прибыль')),
                ('price_salary_fund', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Фонд заработной платы')),
                ('price_final_price', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Общая цена')),
                ('goods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.goods', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар для Битрикс',
                'verbose_name_plural': 'Товар для Битрикс',
            },
        ),
        migrations.CreateModel(
            name='Bitrix_GoodsComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type_of_goods', models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование типа товара')),
                ('type_of_goods', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип товара')),
                ('goods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bitrix_calc.birtrix_goods', verbose_name='Товар')),
                ('nomenclature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.nomenklatura', verbose_name='Номенклатура')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.operationoftechnologicaloperation', verbose_name='Операция производства')),
                ('technology', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.technologicallink', verbose_name='Технология')),
                ('techoperation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.technologicaloperation', verbose_name='Технологическая операция')),
            ],
            options={
                'verbose_name': 'Состав товара',
                'verbose_name_plural': 'Составы товаров',
            },
        ),
        migrations.CreateModel(
            name='Bitrix_GoodsParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type_of_goods', models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование типа товара')),
                ('type_of_goods', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип товара')),
                ('goods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bitrix_calc.birtrix_goods', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Состав товара',
                'verbose_name_plural': 'Составы товаров',
            },
        ),
        migrations.CreateModel(
            name='Bitrix_GoodsParametersInCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=255, verbose_name='Наименование параметра')),
                ('parameter_value', models.CharField(max_length=255, verbose_name='Значение параметра')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bitrix_calc.birtrix_goods', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Параметр изделия в калькуляции',
                'verbose_name_plural': 'Параметры изделий в калькуляции',
            },
        ),
        migrations.CreateModel(
            name='Bitrix_ParametersNormatives',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('overheads', models.CharField(blank=True, max_length=100, null=True, verbose_name='Накладные расходы')),
                ('salary_fund', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фонд зарплаты')),
                ('profit', models.CharField(blank=True, max_length=100, null=True, verbose_name='Прибыль')),
                ('goods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.goods', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Параметр и Норма',
                'verbose_name_plural': 'Параметры и нормы',
            },
        ),
    ]
