# Generated by Django 5.1 on 2024-11-18 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_goodscomposition_name_type_of_goods_and_more'),
        ('bitrix_calc', '0002_alter_birtrix_price_goodscomposition_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='birtrix_goods',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.folder', verbose_name='Папка'),
        ),
    ]
