# Generated by Django 3.2.25 on 2024-11-24 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_calc', '0004_rename_birtrix_goods_bitrix_goods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitrix_Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Наименование кальляции')),
                ('price_material', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Цена за материал')),
                ('price_add_material', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Цена за добавочный материал')),
                ('price_salary', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Заработная плата')),
                ('price_payroll', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Отчисления на заработную плату')),
                ('price_overheads', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Накладные расходы')),
                ('price_cost', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Себестоимость')),
                ('price_profit', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Прибыль')),
                ('price_salary_fund', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Фонд заработной платы')),
                ('price_final_price', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Общая цена')),
            ],
        ),
        migrations.AlterModelOptions(
            name='birtrix_price_goodscomposition',
            options={},
        ),
        migrations.RemoveField(
            model_name='birtrix_price_goodscomposition',
            name='bitrix_goods_name',
        ),
        migrations.RemoveField(
            model_name='birtrix_price_goodscomposition',
            name='goods',
        ),
        migrations.RemoveField(
            model_name='bitrix_goods',
            name='price_add_material',
        ),
        migrations.RemoveField(
            model_name='bitrix_goods',
            name='price_cost',
        ),
        migrations.RemoveField(
            model_name='bitrix_goods',
            name='price_final_price',
        ),
        migrations.RemoveField(
            model_name='bitrix_goods',
            name='price_material',
        ),
        migrations.RemoveField(
            model_name='bitrix_goods',
            name='price_overheads',
        ),
        migrations.RemoveField(
            model_name='bitrix_goods',
            name='price_payroll',
        ),
        migrations.RemoveField(
            model_name='bitrix_goods',
            name='price_profit',
        ),
        migrations.RemoveField(
            model_name='bitrix_goods',
            name='price_salary',
        ),
        migrations.RemoveField(
            model_name='bitrix_goods',
            name='price_salary_fund',
        ),
        migrations.RemoveField(
            model_name='bitrix_goodsparametersincalculation',
            name='goods',
        ),
        migrations.RemoveField(
            model_name='bitrix_goodsparametersincalculation',
            name='parameter_name',
        ),
        migrations.AddField(
            model_name='birtrix_price_goodscomposition',
            name='goods_compostion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bitrix_calc.bitrix_goodscomposition', verbose_name='Состав товара Битрикс для кальляции'),
        ),
        migrations.AddField(
            model_name='bitrix_goodsparametersincalculation',
            name='parameters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bitrix_calc.bitrix_goodsparameters', verbose_name='Параметры калькуляции'),
        ),
        migrations.AlterField(
            model_name='birtrix_price_goodscomposition',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bitrix_parametersnormatives',
            name='goods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bitrix_calc.bitrix_goods', verbose_name='Товар'),
        ),
        migrations.CreateModel(
            name='Bitrix_Calculation_ParametersNormatives',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('overheads', models.CharField(blank=True, default=100, max_length=100, null=True, verbose_name='Накладные расходы')),
                ('salary_fund', models.CharField(blank=True, default=69, max_length=100, null=True, verbose_name='Фонд зарплаты')),
                ('profit', models.CharField(blank=True, default=37, max_length=100, null=True, verbose_name='Прибыль')),
                ('payroll', models.CharField(blank=True, default=40, max_length=100, null=True, verbose_name='Отчисления на зарплату')),
                ('calculation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bitrix_calc.bitrix_calculation', verbose_name='Калькуляция')),
            ],
            options={
                'verbose_name': 'Параметр и Норма для товара для Калькуляции в Битриксе',
                'verbose_name_plural': 'Параметры и нормы для товара для Калькуляции в Битриксе',
            },
        ),
        migrations.AddField(
            model_name='bitrix_calculation',
            name='goods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bitrix_calc.bitrix_goods', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='birtrix_price_goodscomposition',
            name='calculation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bitrix_calc.bitrix_calculation', verbose_name='Калькуляция'),
        ),
        migrations.AddField(
            model_name='bitrix_goodsparametersincalculation',
            name='calculation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bitrix_calc.bitrix_calculation', verbose_name='Калькуляция'),
        ),
    ]
