# Generated by Django 3.0.14 on 2024-11-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_calc', '0005_auto_20241124_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitrix_Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitrix_deal_number', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Номер сделки')),
            ],
        ),
        migrations.AlterField(
            model_name='birtrix_price_goodscomposition',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bitrix_calculation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bitrix_calculation',
            name='name',
            field=models.CharField(editable=False, max_length=100, unique=True, verbose_name='Наименование калькуляции'),
        ),
        migrations.AlterField(
            model_name='bitrix_calculation',
            name='price_final_price',
            field=models.CharField(max_length=100, unique=True, verbose_name='Общая цена'),
        ),
        migrations.AlterField(
            model_name='bitrix_goodscomposition',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bitrix_goodsparameters',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bitrix_goodsparametersincalculation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
