# Generated by Django 5.0.3 on 2024-10-17 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterCalculation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chapter_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование Раздела калькуляции')),
                ('chapter_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Код Раздела калькуляции')),
            ],
        ),
        migrations.CreateModel(
            name='JopTitles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование должности сотрудника')),
            ],
        ),
        migrations.CreateModel(
            name='MeasureUnit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('measure_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование единицы измерения')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Код изделия')),
                ('product_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование изделия')),
            ],
            options={
                'verbose_name': 'Изделие',
                'verbose_name_plural': 'Изделия',
            },
        ),
        migrations.CreateModel(
            name='Nomenklatura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nomenklatura_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Код коменклатуры')),
                ('nomenklatura_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование коменклатуры')),
                ('full_name', models.CharField(blank=True, max_length=400, null=True, verbose_name='Полное наименование')),
                ('comment', models.CharField(blank=True, max_length=400, null=True, verbose_name='Комментарий')),
                ('waste_rate', models.CharField(blank=True, max_length=400, null=True, verbose_name='Норма отходов')),
                ('material_markup', models.CharField(blank=True, max_length=400, null=True, verbose_name='Наценка материала')),
                ('price', models.CharField(blank=True, max_length=400, null=True, verbose_name='Цена номернклатуры')),
                ('measure_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.measureunit', verbose_name='Единица измерения')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Местонахождение', to='base.nomenklatura', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Номенклатура',
                'verbose_name_plural': 'Номенклатура',
            },
        ),
        migrations.CreateModel(
            name='ParametersNormatives',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('overheads', models.CharField(blank=True, max_length=100, null=True, verbose_name='Накладные расходы')),
                ('salary_fund', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фонд зарплаты')),
                ('profit', models.CharField(blank=True, max_length=100, null=True, verbose_name='Прибыль')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.product', verbose_name='Изделие')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionOperation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('operation_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Код операции производства')),
                ('operation_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование операции производства')),
                ('job_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.joptitles', verbose_name='Должность')),
                ('measure_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.measureunit', verbose_name='Единица измерения')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Местонахождение', to='base.productionoperation', verbose_name='Родитель')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionOperationTariffs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lead_time', models.CharField(blank=True, max_length=100, null=True, verbose_name='Время выполнения')),
                ('min_time', models.CharField(blank=True, max_length=100, null=True, verbose_name='Минимальное время')),
                ('preporation_time', models.CharField(blank=True, max_length=100, null=True, verbose_name='Время на подготовку')),
                ('many_people', models.CharField(blank=True, max_length=100, null=True, verbose_name='Количество человек')),
                ('accept_each_product', models.BooleanField(default=False, verbose_name='Применять время подготовки на каждое изделие')),
                ('production_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.productionoperation', verbose_name='Операция производства')),
            ],
        ),
        migrations.CreateModel(
            name='TechnologicalLink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('operation_link_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Код технологического узла')),
                ('operation_link_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование технологического узла')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Местонахождение', to='base.technologicallink', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Техническая операция',
                'verbose_name_plural': 'Технические операции',
            },
        ),
        migrations.CreateModel(
            name='TechnologicalOperation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('operation_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Код технологической операции')),
                ('operation_link_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование технологической операции')),
                ('formula_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Представление в формуле')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Местонахождение', to='base.technologicaloperation', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Технологическая операция',
                'verbose_name_plural': 'Технологические операции',
            },
        ),
        migrations.CreateModel(
            name='TechnologicalLinkComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('technical_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.technologicallink', verbose_name='Технологический узел')),
                ('technical_operation', models.ManyToManyField(blank=True, to='base.technologicaloperation', verbose_name='Технологическая операция')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='ProductComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_selected', models.BooleanField(default=False, verbose_name='Выбран по умолчанию')),
                ('nomenclature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.nomenklatura', verbose_name='Номенклатура')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.product', verbose_name='Изделие')),
                ('technology', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.technologicallink', verbose_name='Технология')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.technologicaloperation', verbose_name='Технологическая операция')),
            ],
            options={
                'verbose_name': 'Состав изделия',
                'verbose_name_plural': 'Составы изделий',
            },
        ),
        migrations.CreateModel(
            name='OperationOfTechnologicalOperation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('formula', models.CharField(blank=True, max_length=100, null=True, verbose_name='Формула расчета')),
                ('production_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.productionoperation', verbose_name='Операция производства')),
                ('technicological_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.technologicaloperation', verbose_name='Технологическая операция')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialsTechnologicalOperation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('formula_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Представление в формуле')),
                ('chapter_calculation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.chaptercalculation', verbose_name='Раздел Калькуляции')),
                ('nomenklatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.nomenklatura', verbose_name='Номенклатура')),
                ('technical_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.technologicaloperation', verbose_name='Технологическая операция')),
            ],
            options={
                'verbose_name': 'Материал технологической операции',
                'verbose_name_plural': 'Материалы технологической операции',
            },
        ),
        migrations.CreateModel(
            name='AddingMaterialsTechnologicalOperation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('formula_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Представление в формуле')),
                ('chapter_calculation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.chaptercalculation', verbose_name='Раздел Калькуляции')),
                ('nomenklatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.nomenklatura', verbose_name='Номенклатура')),
                ('technicological_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.technologicaloperation', verbose_name='Технологическая операция')),
            ],
        ),
    ]
