# Generated by Django 5.0.3 on 2024-10-17 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_addingmaterialstechnologicaloperation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula_name', models.CharField(max_length=100, unique=True, verbose_name='Представление в формуле')),
            ],
            options={
                'verbose_name': 'Формула',
                'verbose_name_plural': 'Формулы',
            },
        ),
        migrations.CreateModel(
            name='ParametersOfProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters_product', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование параметра изделия')),
                ('formula_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Представление в формуле')),
                ('formula', models.CharField(blank=True, max_length=100, null=True, verbose_name='Формула расчета')),
                ('measure_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.measureunit', verbose_name='Единица измерения')),
            ],
        ),
    ]
