# Generated by Django 5.0.3 on 2024-10-17 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_formulas_parametersofproducts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametersofproducts',
            options={'verbose_name': 'Параметр изделия', 'verbose_name_plural': 'Параметры изделия'},
        ),
    ]
