# Generated by Django 5.0.3 on 2024-10-17 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_parametersofproducts_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('calculation_code', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Код калькуляции')),
                ('calculation_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование калькуляции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Калькуляция',
                'verbose_name_plural': 'Калькуляции',
            },
        ),
        migrations.CreateModel(
            name='CalculationComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.calculation', verbose_name='Калькуляция')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.nomenklatura', verbose_name='Номенклатура')),
                ('production_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.productionoperation', verbose_name='Операция производства')),
                ('technological_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.technologicallink', verbose_name='Технологический узел')),
                ('technological_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.technologicaloperation', verbose_name='Технологическая операция')),
            ],
            options={
                'verbose_name': 'Состав калькуляции',
                'verbose_name_plural': 'Составы калькуляций',
            },
        ),
        migrations.CreateModel(
            name='ParametersNormativesInCalculation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('overheads', models.CharField(blank=True, max_length=100, null=True, verbose_name='Накладные расходы')),
                ('salary_fund', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фонд зарплаты')),
                ('profit', models.CharField(blank=True, max_length=100, null=True, verbose_name='Прибыль')),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.calculation', verbose_name='Калькуляция')),
            ],
            options={
                'verbose_name': 'Параметр и Норма в калькуляции',
                'verbose_name_plural': 'Параметры и нормы в калькуляции',
            },
        ),
        migrations.CreateModel(
            name='ProductParametersInCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=255, verbose_name='Наименование параметра')),
                ('parameter_value', models.CharField(max_length=255, verbose_name='Значение параметра')),
                ('quantity_of_products', models.PositiveIntegerField(verbose_name='Количество изделий')),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.calculation', verbose_name='Калькуляция')),
            ],
            options={
                'verbose_name': 'Параметр изделия в калькуляции',
                'verbose_name_plural': 'Параметры изделий в калькуляции',
            },
        ),
    ]
