# Generated by Django 5.0.3 on 2024-10-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_calculation_calculationcomposition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productparametersincalculation',
            name='quantity_of_products',
        ),
        migrations.AlterField(
            model_name='parametersnormativesincalculation',
            name='overheads',
            field=models.CharField(blank=True, default=100, max_length=100, null=True, verbose_name='Накладные расходы'),
        ),
        migrations.AlterField(
            model_name='parametersnormativesincalculation',
            name='profit',
            field=models.CharField(blank=True, default=37, max_length=100, null=True, verbose_name='Прибыль'),
        ),
        migrations.AlterField(
            model_name='parametersnormativesincalculation',
            name='salary_fund',
            field=models.CharField(blank=True, default=69, max_length=100, null=True, verbose_name='Фонд зарплаты'),
        ),
    ]
