# Generated by Django 5.0.3 on 2024-10-18 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_productparametersincalculation_quantity_of_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialstechnologicaloperation',
            name='formula_name',
        ),
    ]
