# Generated by Django 5.0.3 on 2024-10-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_materialstechnologicaloperation_formula_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialstechnologicaloperation',
            old_name='technical_operation',
            new_name='technicological_operation',
        ),
        migrations.RemoveField(
            model_name='addingmaterialstechnologicaloperation',
            name='formula_name',
        ),
        migrations.AddField(
            model_name='addingmaterialstechnologicaloperation',
            name='formula',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Формула расчета'),
        ),
    ]
