# Generated by Django 5.0.3 on 2024-10-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_technical_operation_materialstechnologicaloperation_technicological_operation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addingmaterialstechnologicaloperation',
            name='formula_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Представление в формуле'),
        ),
        migrations.AddField(
            model_name='materialstechnologicaloperation',
            name='formula_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Представление в формуле'),
        ),
        migrations.AddField(
            model_name='operationoftechnologicaloperation',
            name='formula_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Представление в формуле'),
        ),
    ]
