# Generated by Django 5.1 on 2024-10-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_addingmaterialstechnologicaloperation_formula_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersnormativesincalculation',
            name='payroll',
            field=models.CharField(blank=True, default=40, max_length=100, null=True, verbose_name='Отчисления на зарплату'),
        ),
    ]
