# Generated by Django 5.1 on 2024-10-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_parametersnormativesincalculation_payroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='joptitles',
            name='salary',
            field=models.PositiveIntegerField(default=200),
        ),
    ]
