# Generated by Django 5.1 on 2024-10-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_joptitles_salary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nomenklatura',
            options={},
        ),
        migrations.AlterField(
            model_name='nomenklatura',
            name='nomenklatura_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Код номенклатуры'),
        ),
    ]
