# Generated by Django 5.1 on 2024-10-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_nomenklatura_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomenklatura',
            name='nomenklatura_name',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Наименование коменклатуры'),
        ),
    ]
