# Generated by Django 5.1 on 2024-10-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_nomenklatura_nomenklatura_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologicallink',
            name='operation_link_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Код технологического узла'),
        ),
    ]
