# Generated by Django 5.1 on 2024-10-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_technologicallink_operation_link_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nomenklatura',
            options={'verbose_name': 'Номенклатура', 'verbose_name_plural': 'Номенклатура'},
        ),
        migrations.AlterField(
            model_name='technologicaloperation',
            name='operation_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Код технологической операции'),
        ),
    ]
