# Generated by Django 5.1 on 2024-10-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_productionoperation_parent_folder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionoperation',
            name='operation_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Код операции производства'),
        ),
    ]
