# Generated by Django 5.1 on 2024-11-05 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_remove_nomenklatura_parent_nomenklatura_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technologicaloperation',
            name='parent',
        ),
        migrations.AddField(
            model_name='technologicaloperation',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.folder', verbose_name='Папка'),
        ),
    ]
