# Generated by Django 5.1 on 2024-11-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_remove_technologicaloperation_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersofproducts',
            name='formula_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Представление в формуле'),
        ),
    ]
