# Generated by Django 5.1 on 2024-11-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_parametersofproducts_formula_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersofproducts',
            name='formula',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Формула расчета'),
        ),
    ]
