# Generated by Django 5.1 on 2024-11-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_parametersofproducts_formula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addingmaterialstechnologicaloperation',
            name='formula',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Формула расчета'),
        ),
        migrations.AlterField(
            model_name='addingmaterialstechnologicaloperation',
            name='formula_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Представление в формуле'),
        ),
        migrations.AlterField(
            model_name='materialstechnologicaloperation',
            name='formula',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Формула'),
        ),
        migrations.AlterField(
            model_name='operationoftechnologicaloperation',
            name='formula',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Формула расчета'),
        ),
        migrations.AlterField(
            model_name='technologicaloperation',
            name='formula',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Формула расчета'),
        ),
    ]
