# Generated by Django 5.1 on 2024-11-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_addingmaterialstechnologicaloperation_formula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addingmaterialstechnologicaloperation',
            name='formula',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Формула расчета'),
        ),
        migrations.AlterField(
            model_name='materialstechnologicaloperation',
            name='formula',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Формула'),
        ),
        migrations.AlterField(
            model_name='operationoftechnologicaloperation',
            name='formula',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Формула расчета'),
        ),
        migrations.AlterField(
            model_name='parametersofproducts',
            name='formula',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Формула расчета'),
        ),
        migrations.AlterField(
            model_name='technologicaloperation',
            name='formula',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Формула расчета'),
        ),
    ]
