# Generated by Django 5.1 on 2024-11-10 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_addingmaterialstechnologicaloperation_formula_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technologicallink',
            name='parent',
        ),
        migrations.AddField(
            model_name='technologicallink',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.folder', verbose_name='Папка'),
        ),
    ]
