# Generated by Django 5.1 on 2024-11-10 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_remove_technologicallink_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technologicallinkcomposition',
            name='technical_operation',
        ),
        migrations.AddField(
            model_name='technologicallinkcomposition',
            name='technical_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.technologicaloperation', verbose_name='Технологическая операция'),
        ),
    ]
