# Generated by Django 5.1 on 2024-11-12 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_remove_technologicallinkcomposition_technical_operation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomposition',
            name='techoperation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.technologicaloperation', verbose_name='Технологическая операция'),
        ),
        migrations.AlterField(
            model_name='productcomposition',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.operationoftechnologicaloperation', verbose_name='Операция производства'),
        ),
    ]
