# Generated by Django 5.1 on 2024-11-17 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_product_folder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('goods_code', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Код изделия')),
                ('goods_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование изделия')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.folder', verbose_name='Папка')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товар',
            },
        ),
        migrations.CreateModel(
            name='GoodsComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_selected', models.BooleanField(default=False, verbose_name='Выбран по умолчанию')),
                ('goods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.goods', verbose_name='Товар')),
                ('nomenclature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.nomenklatura', verbose_name='Номенклатура')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.operationoftechnologicaloperation', verbose_name='Операция производства')),
                ('technology', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.technologicallink', verbose_name='Технология')),
                ('techoperation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.technologicaloperation', verbose_name='Технологическая операция')),
            ],
            options={
                'verbose_name': 'Состав товара',
                'verbose_name_plural': 'Составы товаров',
            },
        ),
    ]
