# Generated by Django 5.1.3 on 2024-11-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_bitrixuser_refresh_token_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitrixuser',
            name='refresh_token_ttl',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='bitrixuser',
            name='refresh_token_created_at',
            field=models.DateTimeField(),
        ),
    ]
